title: Bharadwaj Mokshagundam
logo: /assets/img/BharadwajPhotograh.jpg
description: Currently working as a CPQ developer and pursuing my masters in Machine Learning and Artificial Intelligence.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
